### ISSUE TITLE
More a support than an issue: purging a specific transient?

### ISSUE THREAD

**Issue by xberg** [bainternet/GWP-Widget-Cache#1]
Hello,
How do I purge a specific transient in PHP?
I see you give transients dynamic names such as WC-6410892e36ed3e271d4532d364201b05
So delete_transient('WC-6410892e36ed3e271d4532d364201b05') would not be a good solution. 
Any suggestion?
Many thanks for the great plugin!

**Comment by bainternet** [comment]
You would need to have the widget instance and arguments in order to generate the same "key" using the `get_widget_key` method or overwrite it to something more specific you can mimic.
